PREFIX esadm: <http://vocab.linkeddata.es/datosabiertos/def/sector-publico/territorio#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT  (COUNT(?municipioAraba) as ?count) 
WHERE { 
	?municipioAraba esadm:provincia ?provincia .
    ?provincia rdfs:label "Araba"@eu .
} 